'use client';
import { useCallback, useEffect, useState } from 'react';

type Row={id:string;full_name?:string;email?:string;phone_whatsapp?:string;stage?:string;source?:string;created_at?:string;next_follow_up_at?:string;patient_id?:string;patient_name?:string;doctor_id?:string;doctor_name?:string;scheduled_for?:string;status?:string;title?:string;starts_at?:string;location?:string;event_type?:string;old_stage?:string;new_stage?:string;actor?:string};
const labels:Record<string,string>={summary:'Visão operacional',leads:'Leads',patients:'Pacientes',appointments:'Consultas',agenda:'Agenda',history:'Histórico',new:'Novo',contact_started:'Contato iniciado',interested:'Interessado',registered:'Cadastrado',confirmed:'Confirmado',reschedule:'Reagendar',lost:'Encerrado',requested:'Solicitado',cancelled:'Cancelado',rescheduled:'Reagendado',attended:'Atendido',no_show:'Não compareceu',paid:'Pago',awaiting_payment:'Aguardando pagamento'};
const tabs=[['summary','crm.access'],['leads','crm.leads.read'],['patients','crm.patients.read'],['appointments','crm.appointments.read'],['agenda','crm.appointments.read'],['history','crm.leads.read']];
const field='mt-1 w-full rounded-xl border border-slate-300 bg-white px-3 py-2.5 text-sm';
const button='rounded-xl bg-[#14508B] px-4 py-2.5 text-sm font-semibold text-white disabled:opacity-50';
const card='rounded-2xl border border-slate-200 bg-white p-5 shadow-sm';
const date=(value?:string)=>value?new Date(value).toLocaleString('pt-BR'):'Não agendado';
const localDate=(value?:string)=>{if(!value)return '';const d=new Date(value);return new Date(d.getTime()-d.getTimezoneOffset()*60000).toISOString().slice(0,16);};

export function CrmConsole({permissions,initialView}:{permissions:string[];initialView:string}) {
  const allowed=tabs.filter(([,p])=>permissions.includes(p));
  const [view,setView]=useState(allowed.some(([v])=>v===initialView)?initialView:'summary');
  const [q,setQ]=useState(''),[offset,setOffset]=useState(0);
  const [items,setItems]=useState<Row[]>([]),[events,setEvents]=useState<Row[]>([]),[doctors,setDoctors]=useState<Row[]>([]);
  const [counts,setCounts]=useState<Record<string,number>>({});
  const [editing,setEditing]=useState<Row|null>(null),[message,setMessage]=useState(''),[busy,setBusy]=useState(false);
  const [patients,setPatients]=useState<Row[]>([]),[patientSearch,setPatientSearch]=useState('');
  const canLead=permissions.includes('crm.leads.manage'),canSchedule=permissions.includes('crm.appointments.manage');
  const load=useCallback(async()=>{
    const response=await fetch(`/api/internal/crm?view=${view}&q=${encodeURIComponent(q)}&offset=${offset}`,{cache:'no-store'});
    const body=await response.json();if(!response.ok)throw new Error(body.message);
    return body;
  },[view,q,offset]);
  useEffect(()=>{let active=true;load().then(data=>{if(active){setItems(data.items??[]);setEvents(data.events??[]);setCounts(data.counts??{});setDoctors(data.doctors??[]);}}).catch(error=>{if(active)setMessage(error.message);});return()=>{active=false;};},[load]);
  useEffect(()=>{
    if(view!=='appointments'||!canSchedule)return;
    let active=true;fetch(`/api/internal/crm?view=patients&q=${encodeURIComponent(patientSearch)}`).then(async response=>{const data=await response.json();if(!response.ok)throw new Error(data.message);if(active)setPatients(data.items);}).catch(error=>{if(active)setMessage(error.message);});return()=>{active=false;};
  },[view,canSchedule,patientSearch]);
  async function save(body:Record<string,unknown>) {
    setBusy(true);setMessage('');try{const response=await fetch('/api/internal/crm',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const result=await response.json();if(!response.ok)throw new Error(result.message);setEditing(null);const data=await load();setItems(data.items??[]);setEvents(data.events??[]);setMessage('Alteração salva e registrada no histórico.');return true;}catch(error){setMessage(error instanceof Error?error.message:'Falha ao salvar.');return false;}finally{setBusy(false);}
  }
  function switchView(value:string){setView(value);setQ('');setOffset(0);setEditing(null);setMessage('');}
  return <div className="space-y-6">
    <div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-[.2em] text-[#15A7DD]">Atendimento e relacionamento</p><h1 className="mt-2 text-3xl font-bold text-[#103E6A]">CRM da equipe</h1><p className="mt-2 text-sm text-slate-500">Organize contatos, acompanhe solicitações e prepare os próximos atendimentos.</p></div><span className="rounded-full border bg-white px-3 py-1 text-xs text-slate-500">Dados da operação</span></div>
    <nav aria-label="Áreas do CRM" className="flex flex-wrap gap-2">{allowed.map(([key])=><button key={key} onClick={()=>switchView(key)} className={`rounded-xl px-4 py-2.5 text-sm font-semibold ${view===key?'bg-[#103E6A] text-white':'border border-slate-200 bg-white text-slate-600'}`}>{labels[key]}</button>)}</nav>
    {message&&<p role="status" className="rounded-xl border border-blue-200 bg-blue-50 p-4 text-sm">{message}</p>}
    {view==='summary'?<><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-5">{Object.entries(counts).map(([key,value])=><div key={key} className={card}><p className="text-sm text-slate-500">{{leads:'Leads cadastrados',new_leads:'Novos leads',patients:'Pacientes',today:'Atendimentos hoje',pending:'Solicitações pendentes'}[key]}</p><p className="mt-3 text-3xl font-bold text-[#103E6A]">{value}</p></div>)}</div><section className={card}><h2 className="font-bold text-[#103E6A]">Sua fila de trabalho</h2><p className="mt-2 text-sm text-slate-500">Use Leads para registrar contatos e Consultas para organizar os atendimentos. A agenda reúne consultas e compromissos compartilhados com a equipe.</p></section></>:<section className={card}>
      <label className="text-sm font-semibold">Pesquisar por nome ou contato<input className={field} value={q} onChange={event=>{setQ(event.target.value);setOffset(0);}} placeholder="Pesquisar..."/></label>
      <div className="mt-5 overflow-x-auto"><table className="w-full text-left text-sm"><thead className="border-b text-xs uppercase tracking-wide text-slate-500"><tr><th className="px-3 py-3">{view==='agenda'?'Atendimento':'Registro'}</th><th className="px-3">{view==='history'?'Alteração':'Contato / profissional'}</th><th className="px-3">Status / data</th><th className="px-3">Ações</th></tr></thead>
        <tbody>{items.map(item=><tr key={item.id} className="border-b border-slate-100"><td className="px-3 py-4 font-semibold">{item.full_name||item.patient_name}</td><td className="px-3 py-4 text-slate-500">{view==='history'?`${labels[item.old_stage??'']||'—'} → ${labels[item.new_stage??'']||'—'}`:<>{item.doctor_name||item.email||'—'}<br/>{item.phone_whatsapp}</>}</td><td className="px-3 py-4">{labels[item.stage||item.status||'']||item.event_type||'Cadastrado'}<p className="mt-1 text-xs text-slate-500">{date(item.scheduled_for||item.next_follow_up_at||item.created_at)}</p></td><td className="px-3 py-4">{((view==='leads'&&canLead)||(view==='appointments'&&canSchedule))&&<button className="font-semibold text-[#14508B]" onClick={()=>setEditing(item)}>Editar</button>}</td></tr>)}</tbody></table></div>
      {!items.length&&<p className="py-10 text-center text-sm text-slate-500">Nenhum registro encontrado nesta área.</p>}
      <div className="mt-4 flex justify-between text-sm"><button disabled={!offset} onClick={()=>setOffset(Math.max(0,offset-100))}>← Anterior</button><span>{items.length} registros nesta página</span><button disabled={items.length<100} onClick={()=>setOffset(offset+100)}>Seguinte →</button></div>
    </section>}
    {view==='leads'&&canLead&&<section className={card}><h2 className="mb-4 text-lg font-bold">{editing?'Editar acompanhamento':'Novo lead'}</h2><form key={editing?.id??'new-lead'} className="grid gap-4 md:grid-cols-2" onSubmit={async event=>{event.preventDefault();const form=event.currentTarget;const f=new FormData(form);if(await save({operation:'lead',id:editing?.id,fullName:f.get('fullName'),email:f.get('email'),phone:f.get('phone'),stage:f.get('stage'),nextFollowUp:f.get('nextFollowUp')?new Date(String(f.get('nextFollowUp'))).toISOString():null}))form.reset();}}>
      <label>Nome<input name="fullName" className={field} required minLength={2} maxLength={160} defaultValue={editing?.full_name}/></label><label>E-mail<input name="email" type="email" className={field} defaultValue={editing?.email}/></label><label>WhatsApp<input name="phone" className={field} maxLength={40} defaultValue={editing?.phone_whatsapp}/></label><label>Etapa<select name="stage" className={field} defaultValue={editing?.stage||'new'}>{editing?.stage&&['paid','awaiting_payment'].includes(editing.stage)&&<option value={editing.stage}>{labels[editing.stage]} (estado preservado)</option>}{['new','contact_started','interested','registered','confirmed','reschedule','lost'].map(key=><option key={key} value={key}>{labels[key]}</option>)}</select></label><label>Próximo contato<input name="nextFollowUp" type="datetime-local" className={field} defaultValue={localDate(editing?.next_follow_up_at)}/></label><div className="flex items-end gap-4"><button disabled={busy} className={button}>Salvar lead</button>{editing&&<button type="button" onClick={()=>setEditing(null)}>Cancelar</button>}</div>
    </form></section>}
    {view==='appointments'&&canSchedule&&<section className={card}><h2 className="mb-4 text-lg font-bold">{editing?'Organizar atendimento':'Novo agendamento'}</h2>{!editing&&<label className="text-sm">Localizar paciente<input className={field} value={patientSearch} onChange={event=>setPatientSearch(event.target.value)} placeholder="Nome ou contato do paciente"/></label>}<form key={editing?.id??'new-appointment'} className="mt-4 grid gap-4 md:grid-cols-2" onSubmit={async event=>{event.preventDefault();const form=event.currentTarget;const f=new FormData(form);if(await save({operation:'appointment',id:editing?.id,patientId:editing?.patient_id||f.get('patientId'),doctorId:f.get('doctorId'),status:f.get('status'),scheduledFor:f.get('scheduledFor')?new Date(String(f.get('scheduledFor'))).toISOString():null}))form.reset();}}>
      <label>Paciente{editing?<p className="mt-3 font-semibold">{editing.patient_name}</p>:<select name="patientId" required className={field}><option value="">Selecione um paciente cadastrado</option>{patients.map(patient=><option key={patient.id} value={patient.id}>{patient.full_name}</option>)}</select>}</label><label>Médico<select name="doctorId" className={field} defaultValue={editing?.doctor_id||''}><option value="">A definir</option>{doctors.map(doctor=><option key={doctor.id} value={doctor.id}>{doctor.full_name}</option>)}</select></label><label>Data e horário<input name="scheduledFor" type="datetime-local" className={field} defaultValue={localDate(editing?.scheduled_for)}/></label><label>Status<select name="status" className={field} defaultValue={editing?.status||'requested'}>{editing?.status&&['paid','awaiting_payment'].includes(editing.status)&&<option value={editing.status}>{labels[editing.status]} (estado preservado)</option>}{['requested','confirmed','cancelled','rescheduled','attended','no_show'].map(key=><option key={key} value={key}>{labels[key]}</option>)}</select></label><div className="flex gap-4"><button disabled={busy} className={button}>Salvar agendamento</button>{editing&&<button type="button" onClick={()=>setEditing(null)}>Cancelar edição</button>}</div>
    </form></section>}
    {view==='agenda'&&<section className={card}><h2 className="text-lg font-bold">Compromissos da equipe</h2><div className="my-4 space-y-3">{events.map(event=><div key={event.id} className="rounded-xl border border-slate-200 p-3"><p className="font-semibold">{event.title}</p><p className="text-sm text-slate-500">{date(event.starts_at)} · {event.location||'Local a definir'}</p></div>)}{!events.length&&<p className="text-sm text-slate-500">Nenhum compromisso operacional cadastrado.</p>}</div>{canSchedule&&<form className="grid gap-4 md:grid-cols-3" onSubmit={async event=>{event.preventDefault();const form=event.currentTarget;const f=new FormData(form);if(await save({operation:'event',title:f.get('title'),startsAt:new Date(String(f.get('startsAt'))).toISOString(),location:f.get('location')}))form.reset();}}><label>Compromisso<input name="title" className={field} required minLength={2} maxLength={160}/></label><label>Data e horário<input name="startsAt" type="datetime-local" className={field} required/></label><label>Local<input name="location" className={field} maxLength={160}/></label><button className={button} disabled={busy}>Compartilhar compromisso</button></form>}</section>}
  </div>;
}
